### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by flexseth**
Adds a GPL v2 license in the base folder of the software repository, covering all software within.

### CODE REVIEW

**Comment by juanmaguitar** [comment]
@flexseth There's a `.anima/.gitgnore` file that shouldn't be part of this PR.

**Comment by flexseth** [comment]
> @flexseth There's a `.anima/.gitgnore` file that shouldn't be part of this PR.

Removed the file, should be G2G.

**Review by juanmaguitar — APPROVED** [review]

**Comment by juanmaguitar** [comment]
LGTM! 👍

**Comment by flexseth** [comment]
Sounds good, moving on to other stuff. I'll probably have more contributions to this repo as time permits!

Best/Seth

**Pull request merged**
