### PR TITLE
Live demo in Basic Block tutorial – redirect to a post with a live block example

### PR DESCRIPTION
**Pull request by adamziel**
The current Live Demo link redirects to the plugins page, which isn't very helpful to a new person trying to interact with the block. This PR updates the link so that it redirects the user to an actual live example.

The Blueprint used in this PR is:

```json
{
  "landingPage": "/wp-admin/post.php?post=4&action=edit",
  "steps": [
    {
      "step": "login",
      "username": "admin",
      "password": "password"
    },
    {
      "step": "mkdir",
      "path": "/downloads"
    },
    {
      "step": "writeFile",
      "path": "/downloads/plugin.zip",
      "data": {
        "resource": "url",
        "url": "https://raw.githubusercontent.com/WordPress/block-development-examples/deploy/zips/basic-esnext-a2ab62.zip",
        "caption": "Downloading plugin..."
      }
    },
    {
      "step": "installPlugin",
      "pluginZipFile": {
        "resource": "vfs",
        "path": "/downloads/plugin.zip"
      }
    },
    {
      "step": "runPHP",
      "code": "<?php require '/wordpress/wp-load.php'; wp_insert_post( array('post_title'    => 'Test block','post_content'  => '<!-- wp:block-development-examples/basic-esnext-a2ab62 --><div style=\"background-color:#900;color:#fff;padding:20px\" class=\"wp-block-block-development-examples-basic-esnext-a2ab62\">Hello World, step 1 (from the frontend).</div><!-- /wp:block-development-examples/basic-esnext-a2ab62 -->', 'post_status'   => 'publish', 'post_author'   => 1 ) );"
    }
  ]
}
```

## Testing instructions

1. Preview the changes
2. Click the Live Demo link
3. Confirm it shows this view:

CleanShot 2023-12-10 at 13 13 08@2x

Repeat for the "no build" example.

## Caveats

The `landingPage` link contains a hardcoded post ID right now. It's not ideal, as a future WordPress release could ship with different starter content and break that redirection. Playground will need to provide a mechanism for redirecting to a specific post, regardless of its relative ID.

I started an issue to track it here:

https://github.com/WordPress/blueprints/issues/52

### CODE REVIEW

**Comment by adamziel** [comment]
Yay, it took some attempts to get that link to work in Markdown, but it finally does! The trick is to double escape the double quotes in json, e.g. do `\\"` and not `\"`. This one is ready, feel free to merge.

**Comment by juanmaguitar** [comment]
HI @adamziel 
Thanks for opening this PR.
We recently started using custom blueprints in some of the examples (`_playground/blueprint.json` file inside the example folder) and we have plans to add custom blueprints for ALL the examples in the following weeks. 

The playground links are generated automatically using internal scripts ( `npm run table:update:all`) so updating links directly in the markdown won't work as they will be overwritten next time the links are generated. The current way to properly add custom `blueprint.json` to add it to the `_playground/blueprint.json` path and run  `npm run table:update:all` from the root to regenerate the links. When blueprints are detected in an example folder, the proper playground link to use that blueprint are generated in the table when doing `npm run table:update:all`

The current examples with custom blueprints are:
- [`minimal-block-ca6eda`](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/minimal-block-ca6eda)
- [block-supports-6aa4dd](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/block-supports-6aa4dd)
- [copyright-date-block-09aac3](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/copyright-date-block-09aac3)
- [data-basics-59c8f8](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/data-basics-59c8f8)
- [interactivity-api-block-833d15](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/interactivity-api-block-833d15)
- [minimal-block-ca6eda](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/interactivity-api-block-833d15)
- [stylesheets-79a4c3](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/stylesheets-79a4c3)

These examples provide a better experience with the playground live demo as they take you to the frontend view of the example or the Block Editor with the block inserted

Maybe these examples are enough as use cases to show how Playground can be applied to show specific plugins. If you want to add more you just have to add the custom playground in the path `_playground/blueprint.json` inside the examples folder and run `npm run table:update:all` from the root of the project to regenerate the links of playground.

**Comment by adamziel** [comment]
@juanmaguitar I just updated this PR, please let me know if I got that right.

**Review by juanmaguitar — APPROVED** [review]

**Comment by juanmaguitar** [comment]
LGTM! ✅

**Pull request merged**
